DROP TABLE TABELA_VENDEDORES

CREATE TABLE [dbo].[TABELA_VENDEDORES](
	[MATRICULA] [varchar](5) NOT NULL,
	[NOME] [varchar](100) NULL,
	[PERCENTUAL_COMISSAO] [float] NULL,
	DATA_ADMISSAO SMALLINT NULL,
	ESTA_FERIAS VARCHAR(50),
 CONSTRAINT [PK_VENDEDORES] PRIMARY KEY CLUSTERED 
(
	[MATRICULA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

