
CREATE TABLE [TABELA_CLIENTES](
	[CPF][VARCHAR](11),
	[NOME][VARCHAR](100), 
	[ENDEREÇO_1][VARCHAR](100),
	[ENDEREÇO_2][VARCHAR](100),
	[BAIRRO][VARCHAR](50),
	[CIDADE][VARCHAR](50),
	[ESTADO][VARCHAR](3),
	[CEP][VARCHAR](8),
	[DATA_NACIMENTO][SMALLINT],
	[SEXO][VARCHAR](1),
	[LIMITE_CREDITO][MONEY],
	[VOLUME_COMPRA][FLOAT],
	[PRIMEIRA_COMPRA][BIT])

CREATE TABLE TABELA_VENDEDORES(
	MATRICULA VARCHAR(5),
	NOME VARCHAR(100),
	PERCENTUAL_COMISSAO FLOAT)

CREATE TABLE TABELA_PRODUTO_3(
	CODIGO_PRODUTO VARCHAR(10),
	NOME_PRODUTO VARCHAR(50),
	EMBALAGEM VARCHAR(20),
	TAMANHO VARCHAR(10),
	SABOR VARCHAR (20),
	PREÇO_LISTA SMALLMONEY)

