INSERT INTO TABELA_PRODUTO(
CODIGO_PRODUTO, NOME_PRODUTO, EMBALAGEM, TAMANHO, SABOR, PREÇO_LISTA) 
VALUES('1040107', 'LIGHT - 350ML - Melância', 'lata', 'Melância', '350ml', 4.56)

INSERT INTO TABELA_PRODUTO(
CODIGO_PRODUTO, NOME_PRODUTO, EMBALAGEM, TAMANHO, SABOR, PREÇO_LISTA) 
VALUES('1037797', 'Clean - 2 Litros - Laranja', 'PET', '2 litros', 'Laranja', 16.01)


INSERT INTO TABELA_VENDEDORES(
MATRICULA, NOME, PERCENTUAL_COMISSAO)
VALUES('0023','José Geraldo da Fonseca', 0.10)

INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSÃO])
VALUES
('00235','Márcio Almeida Silva',0.08)

INSERT INTO [TABELA DE VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSÃO])
VALUES
('00236','Cláudia Morais',0.08)

UPDATE TABELA_PRODUTO SET
EMBALAGEM = 'LATA',
PREÇO_LISTA = 2.46
WHERE CODIGO_PRODUTO = '1040107'

SELECT * FROM TABELA_PRODUTO