ALTER TABLE TABELA_VENDEDORES
ALTER COLUMN DATA_ADMISSAO
VARCHAR(10)

INSERT INTO TABELA_VENDEDORES 
			(MATRICULA
			,NOME
			,PERCENTUAL_COMISSAO
			,DATA_ADMISSAO
			,ESTA_FERIAS)
		VALUES
			('00235'
			,'Márcio Almeida Silva'
			,'0.08'
			,'2014-08-15'
			,'sim')

INSERT INTO TABELA_VENDEDORES 
			(MATRICULA
			,NOME
			,PERCENTUAL_COMISSAO
			,DATA_ADMISSAO
			,ESTA_FERIAS)
		VALUES
			('00236'
			,'Cláudia Morais'
			,'0.08'
			,'2013-09-17'
			,'sim')

INSERT INTO [TABELA_VENDEDORES]
([MATRICULA], [NOME], [DATA_ADMISSAO], [PERCENTUAL_COMISSAO], [ESTA_FERIAS])
VALUES
('00237','Roberta Martins','2017-03-18',0.11,1)

INSERT INTO [TABELA_VENDEDORES]
([MAtRICULA], [NOME], [DATA_ADMISSAO], [PERCENTUAL_COMISSAO], [ESTA_FERIAS])
VALUES
('00238','Pericles Alves','2016-08-21',0.11,0)

