INSERT INTO [TABELA_PRODUTO]
([CODIGO_PRODUTO], [NOME_PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PREÇO_LISTA])
VALUES
('1040107','Light - 350 ml - Melancia', 'Lata', '350 ml', 'Melancia', 4.56)

INSERT INTO [TABELA_PRODUTO]
([CODIGO_PRODUTO], [NOME_PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PREÇO_LISTA])
VALUES
('1037797','Clean - 2 Litros - Laranja', 'PET', '2 Litros', 'Laranja', 16.01)

INSERT INTO [TABELA_PRODUTO]
([CODIGO_PRODUTO], [NOME_PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PREÇO_LISTA])
VALUES
('1000889','Sabor da Montanha - 700 ml - Uva', 'Garrafa', '700 ml', 'Uva', 6.31)