INSERT INTO TABELA_PRODUTO(
CODIGO_PRODUTO, NOME_PRODUTO, EMBALAGEM, TAMANHO, SABOR, PREÇO_LISTA) 
VALUES('1040107', 'LIGHT - 350ML - Melância', 'lata', 'Melância', '350ml', 4.56)

INSERT INTO TABELA_PRODUTO(
CODIGO_PRODUTO, NOME_PRODUTO, EMBALAGEM, TAMANHO, SABOR, PREÇO_LISTA) 
VALUES('1040107', 'SEGUNDO', 'SEGUNDO', 'SEGUNDO', 'SEGUNDO', 2)

DELETE FROM TABELA_PRODUTO
WHERE NOME_PRODUTO = 'SEGUNDO'

SELECT * FROM TABELA_PRODUTO


ALTER TABLE TABELA_PRODUTO
ALTER COLUMN CODIGO_PRODUTO
VARCHAR(10) NOT NULL

ALTER TABLE TABELA_PRODUTO
ADD CONSTRAINT PK_PRODUTOS
PRIMARY KEY CLUSTERED(CODIGO_PRODUTO)


SELECT * FROM TABELA_VENDEDORES

ALTER TABLE TABELA_VENDEDORES
ALTER COLUMN MATRICULA
VARCHAR(5) NOT NULL

ALTER TABLE TABELA_VENDEDORES
ADD CONSTRAINT PK_VENDEDORES
PRIMARY KEY CLUSTERED(MATRICULA)




SELECT * FROM TABELA_CLIENTES

ALTER TABLE TABELA_CLIENTES
ALTER COLUMN CPF
VARCHAR(10) NOT NULL

ALTER TABLE TABELA_CLIENTES
ADD CONSTRAINT PK_CLIENTES
PRIMARY KEY CLUSTERED(CPF)

ALTER TABLE TABELA_CLIENTES
ALTER COLUMN CEP
VARCHAR(10) NOT NULL

