SELECT * FROM [TABELA DE PRODUTOS]

SELECT * FROM [TABELA DE PRODUTOS] WHERE EMBALAGEM = 'PET'

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] = 4.555
SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] <> 4.555
SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] > 4.555
SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] < 4.555

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] <= 4.555 AND [PREÇO DE LISTA] >= 4.555 

SELECT * FROM [TABELA DE PRODUTOS] WHERE EMBALAGEM < 'Lata'
SELECT * FROM [TABELA DE PRODUTOS] WHERE EMBALAGEM > 'Lata'
SELECT * FROM [TABELA DE PRODUTOS] WHERE EMBALAGEM <> 'Lata'

SELECT * FROM TABELA_VENDEDORES WHERE PERCENTUAL_COMISSAO > 0.10