USE AdventureWorksLT2019_PT

SELECT * FROM 
(SELECT 
ISNULL(VENDA.ENDERECO.LINHA_ENDERECO2, VENDA.ENDERECO.LINHA_ENDERECO) AS ENDERECO,
SUBSTRING(VENDA.ENDERECO.LINHA_ENDERECO, 1, 4) AS NUMERO_ENDERECO,
LOWER(VENDA.ENDERECO.CIDADE) AS CIDADE_MIN,
UPPER(VENDA.ENDERECO.ESTADO) AS ESTADO_MAX,
SUBSTRING (UPPER(VENDA.ENDERECO.REGIAO),1 , 2) AS REGIAO, VENDA.CLIENTE_ENDERECO.ID_ENDERECO,
CASE 
WHEN VENDA.CLIENTE_ENDERECO.TIPO_ENDERECO = 'main office' then 'principal'
when venda.CLIENTE_ENDERECO.TIPO_ENDERECO = 'shipping' then 'entrega' end TIPO_ENDERECO
FROM VENDA.ENDERECO
LEFT JOIN VENDA.CLIENTE_ENDERECO ON VENDA.ENDERECO.ID_ENDERECO = VENDA.CLIENTE_ENDERECO.ID_ENDERECO)
ENDERECO

