--- nome: Igor Luan Teles de Souza
--- ra: 1905365


USE MASTER
USE AdventureWorksLT2019_PT


---1
CREATE VIEW ENDERECO_CLIENTE
AS
	SELECT DISTINCT
		ISNULL(LINHA_ENDERECO2,LINHA_ENDERECO) ENDERECO_PRINCIPAL,
		SUBSTRING(TRIM(LINHA_ENDERECO),0,CHARINDEX(' ',TRIM(LINHA_ENDERECO))) NUMERO,
		LOWER(CIDADE) MINUSCULO,
		UPPER(ESTADO) MAIUSCULO,
		LEFT(REGIAO, 2) REGIAO,
		CASE WHEN VENDA.CLIENTE_ENDERECO.TIPO_ENDERECO = 'MAIN OFFICE' THEN 'PRINCIPAL'
WHEN VENDA.CLIENTE_ENDERECO.TIPO_ENDERECO = 'SHIPPING' THEN 'ENTREGA' END  TIPO_ENDERECO
	FROM VENDA.ENDERECO
		INNER JOIN VENDA.CLIENTE_ENDERECO
		ON VENDA.ENDERECO.ID_ENDERECO = VENDA.CLIENTE_ENDERECO.ID_ENDERECO

SELECT *
FROM ENDERECO_CLIENTE


---2
CREATE PROCEDURE PEDIDOS_FECHADOS
AS
BEGIN
	SELECT
		VENDA.PRODUTO.NOME,
		ISNULL(VENDA.PRODUTO.COR, 'GREY') COR,
		LUCRO = ((VENDA.PRODUTO.PRECO_LISTA * VENDA.DETALHE_PEDIDO.QUANTIDADE_PEDIDO)-(VENDA.DETALHE_PEDIDO.PRECO_UNITARIO * VENDA.DETALHE_PEDIDO.QUANTIDADE_PEDIDO)- VENDA.DETALHE_PEDIDO.DESCONTO_UNITARIO),
		DATEDIFF(YEAR,VENDA.PRODUTO.DATA_TERMINO_VENDA,GETDATE()) TEMPO_PARADO,
		DATEDIFF(MONTH,VENDA.PRODUTO.DATA_INICIO_VENDA,DATA_TERMINO_VENDA) CICLO_VIDA,
		DATENAME(MONTH,VENDA.PRODUTO.DATA_TERMINO_VENDA) MES_FIM,
		DATEADD(MONTH,3,VENDA.PRODUTO.DATA_TERMINO_VENDA) TERMINO_ESTOQUE
	FROM VENDA.PRODUTO, VENDA.DETALHE_PEDIDO
	WHERE DATA_TERMINO_VENDA IS NOT NULL
END

EXEC PEDIDOS_FECHADOS


---5
CREATE PROCEDURE ATUALIZA_CLIENTE
AS
BEGIN
	SELECT *
	INTO VENDA.CLIENTE_UPPER
	FROM VENDA.CLIENTE


	UPDATE VENDA.CLIENTE_UPPER
SET TITULO = UPPER(TITULO)

	UPDATE VENDA.CLIENTE_UPPER
SET PRIMEIRO_NOME = UPPER(PRIMEIRO_NOME)

	UPDATE VENDA.CLIENTE_UPPER
SET MEIO_NOME = UPPER(MEIO_NOME)

	UPDATE VENDA.CLIENTE_UPPER
SET ULTIMO_NOME = UPPER(ULTIMO_NOME)

	UPDATE VENDA.CLIENTE_UPPER
SET SUFIXO = UPPER(SUFIXO)

	UPDATE VENDA.CLIENTE_UPPER
SET COMPANHIA = UPPER(COMPANHIA)

	UPDATE VENDA.CLIENTE_UPPER
SET VENDEDOR = UPPER(VENDEDOR)

	UPDATE VENDA.CLIENTE_UPPER
SET EMAIL = UPPER(EMAIL)

	UPDATE VENDA.CLIENTE_UPPER
SET TELEFONE = UPPER(TELEFONE)

	UPDATE VENDA.CLIENTE_UPPER
SET TELEFONE_HASH = UPPER(TELEFONE_HASH)

	UPDATE VENDA.CLIENTE_UPPER
SET PASSWORD = UPPER(PASSWORD)

	UPDATE VENDA.CLIENTE_UPPER
SET ROWGUID = UPPER(ROWGUID)

	UPDATE VENDA.CLIENTE_UPPER
SET DATA_MODIFICACAO = UPPER(DATA_MODIFICACAO)
END

EXEC ATUALIZA_CLIENTE

